apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ctr-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/EvgeniiMunin/ctr_project_part2.git
    targetRevision: HEAD
    path: argocd/app

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuber

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true