apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctr-deploy
  labels:
    app: kuber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctr-app
    template:
      metadata:
        labels:
          app: ctr-app
      spec:
        containers:
          - name: ctr-app
            image: evgeniimunin/ctr_online_inference:v3
            ports:
              - containerPort: 8000
        imagePullSecrets:
          - name: regcred