apiVersion: v1
kind: Pod
metadata:
  name: ctr-app
  labels:
    app: ctr-app
spec:
  containers:
    - image: evgeniimunin/ctr_online_inference:v3
      name: ctr-app
      ports:
        - containerPort: 8000
  imagePullSecrets:
    - name: regcred
