apiVersion: v1
kind: Pod
metadata:
  name: ctr-app-kube-resource
  labels:
    app: ctr-app-kube-resource
spec:
  containers:
    - image: evgeniimunin/ctr_online_inference:v3
      name: ctr-app-kube-resource
      ports:
        - containerPort: 8000
      resources:
        # desired requests
        requests:
          memory: "1Gi"
          cpu: "200m"
        # high limits
        limits:
          memory: "2Gi"
          cpu: "200m"

  imagePullSecrets:
    - name: regcred